# Site settings
title: Tharsis Souza, PhD
email: souza.tharsis [at] gmail [dot] com
description: > # this means to ignore newlines until "baseurl:"
  New York <br> 2025  
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "souzatharsis.github.io" # the base hostname & protocol for your site
twitter_username: souzatharsis
github_username:  tharsissouza
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

# needed for CI builds:
exclude: [vendor]

plugins:
  - jekyll-seo-tag
