# Site settings
title: Thársis T. P. Souza
email: T.Souza@cs.ucl.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  I'm a Ph.D. Candidate in Financial Computing and Analytics at the University College London. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "souzatharsis.github.io" # the base hostname & protocol for your site
twitter_username: souzatharsis
github_username:  souzatharsis
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

# needed for CI builds:
exclude: [vendor]
