# Site settings
title: Thársis T. P. Souza
email: souza.tharsis [at] gmail [dot] com
description: > # this means to ignore newlines until "baseurl:"
  Alternative Data, AI, Financial Computing and Analytics 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "souzatharsis.github.io" # the base hostname & protocol for your site
twitter_username: souzatharsis
github_username:  tharsissouza
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

# needed for CI builds:
exclude: [vendor]
